
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSrightINDIVIDE EQUALS ID IN LET LPAREN MINUS NUMBER PLUS RPAREN TIMESexp : LET ID EQUALS exp IN expexp : exp PLUS exp\n                  | exp MINUS exp\n                  | exp TIMES exp\n                  | exp DIVIDE expexp : MINUS exp %prec UMINUSexp : LPAREN exp RPARENexp : NUMBERexp : ID'
    
_lr_action_items = {'LET':([0,4,5,7,8,9,10,18,21,],[2,2,2,2,2,2,2,2,2,]),'MINUS':([0,1,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,22,],[4,8,-9,4,4,-8,4,4,4,4,-6,8,-2,-3,-4,-5,4,-7,8,4,-1,]),'LPAREN':([0,4,5,7,8,9,10,18,21,],[5,5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,18,21,],[6,6,6,6,6,6,6,6,6,]),'ID':([0,2,4,5,7,8,9,10,18,21,],[3,11,3,3,3,3,3,3,3,3,]),'$end':([1,3,6,12,14,15,16,17,19,22,],[0,-9,-8,-6,-2,-3,-4,-5,-7,-1,]),'PLUS':([1,3,6,12,13,14,15,16,17,19,20,22,],[7,-9,-8,-6,7,-2,-3,-4,-5,-7,7,-1,]),'TIMES':([1,3,6,12,13,14,15,16,17,19,20,22,],[9,-9,-8,-6,9,9,9,-4,-5,-7,9,-1,]),'DIVIDE':([1,3,6,12,13,14,15,16,17,19,20,22,],[10,-9,-8,-6,10,10,10,-4,-5,-7,10,-1,]),'RPAREN':([3,6,12,13,14,15,16,17,19,22,],[-9,-8,-6,19,-2,-3,-4,-5,-7,-1,]),'IN':([3,6,12,14,15,16,17,19,20,22,],[-9,-8,-6,-2,-3,-4,-5,-7,21,-1,]),'EQUALS':([11,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,4,5,7,8,9,10,18,21,],[1,12,13,14,15,16,17,20,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> LET ID EQUALS exp IN exp','exp',6,'p_exp_let','parser.py',78),
  ('exp -> exp PLUS exp','exp',3,'p_exp_binop','parser.py',82),
  ('exp -> exp MINUS exp','exp',3,'p_exp_binop','parser.py',83),
  ('exp -> exp TIMES exp','exp',3,'p_exp_binop','parser.py',84),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp_binop','parser.py',85),
  ('exp -> MINUS exp','exp',2,'p_exp_uminus','parser.py',89),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_group','parser.py',93),
  ('exp -> NUMBER','exp',1,'p_exp_number','parser.py',97),
  ('exp -> ID','exp',1,'p_exp_id','parser.py',101),
]
